apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-rtoy
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0009-tenant/tkrw-pr712-0075-0009-app/devfile-sample-rtoy@sha256:82182011cad0e2de13a2776e749b8ae4c12b4631d4c726f7a19a4e980252228f
        name: my-nodejs
        resources: {}
status: {}
